### ISSUE TITLE
How to change ResourceManager UI Port from 8088, say 9088

### ISSUE THREAD

**Issue by nmvega** [big-data-europe/docker-hadoop#100]
Dear Friends:

My system already uses port `8088` for another service. What steps do I take to change use of port `8088` by the `ResourceManager` `WebUI` to something else (say, to `9088`). I looked at the `hadoop.env` file, but couldn't find a setting for it.

Also, if any other component in the `hadoop` stack need to know about this change to `ResouceManager port`, please let me know how to inform them, too. `=:)`

Thank you!

**Comment by nmvega** [comment]
According to [Apache](https://hadoop.apache.org/docs/r3.2.1/hadoop-project-dist/hadoop-common/ClusterSetup.html), I believe I can accomplish this by updating  `/etc/hadoop/yarn-site.xml` (and perhaps for completeness also `/opt/hadoop-3.2.1/etc/hadoop/yarn-site.xml`), during the build of [this `Dockerfile` file](https://github.com/big-data-europe/docker-hadoop/blob/master/resourcemanager/Dockerfile) (i.e make the updates there).

The directive to modify is: `yarn.resourcemanager.webapp.address`.

Next, I'd have to change all references `8088` to, say, `9088` everywhere `bde2020` references it. This includes in [this `Dockerfile`](https://github.com/big-data-europe/docker-hadoop/blob/master/resourcemanager/Dockerfile) and in [this `docker-compose.yml` file](https://github.com/big-data-europe/docker-hadoop/blob/master/docker-compose.yml).

Does that seem correct? Did I miss other locations that need updating, or other `service components` that need updating as well (e.g. because they may rely on well-known `8088`)?

Thank you in advance! `=:)`

**Comment by m8928** [comment]
Unless you are using the same port in one container, you can do something like this
Change only the ports that are exposed outside the container.

```
resourcemanager: 
  image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
  container_name: resourcemanager 
  ports: 
    -9088:8088 
  restart: always
  environment: 
    SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864" 
  env_file: - ./hadoop.env
```
