### ISSUE TITLE
How can I change the bde2020/docker-hadoop image?

### ISSUE THREAD

**Issue by Benjaminbakir** [big-data-europe/docker-hadoop#116]
Hello,

I am currently using your bde2020/docker-hadoop image and I would like to install Apache flume on it.
I try to fork your image but when I do that and use it inside my docker-compose.yml file I get a constant error, even though when I fork the image I don't apply any changes to the image.

The error I get is: 
check for namenode:9870...
datanode1        | [4/100] namenode:9870 is not available yet
datanode1        | [4/100] try in 5s once again ...

Does someone know why this happens and how to solve it?

**Comment by xxrlzzz** [comment]
did you pair your datanode with a namenode?

some thing like this
```
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"
```
