### ISSUE TITLE
How to fix hdfs url's on web

### ISSUE THREAD

**Issue by Kartonatic** [big-data-europe/docker-hadoop#19]
First of all, thank you very much for this repository. I used your docker-compose and I had a problem on the HDFS web. If you use the hdfs browser on the web, you can't download files. If you want to repair that, you can use a network for hadoop and IP addresses in docker-compose. Afterwards, you have to use 'hostname: ASSIGND_IP' for each container. I use it for the thesis of my master.

https://github.com/Kartonatic/tfm

**Comment by ttimasdf** [comment]
Not that complicated. Use compose file template to automatically apply the hostname to datanode containers is sufficient.

Part of compose file for use with `docker stack deploy`

```yaml
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    networks:
      - hdfs
    hostname: "{{.Node.Hostname}}"
    ports:
      - target: 50075
        published: 50075
        mode: host
    volumes:
      - /hdfsdata:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
```
