### ISSUE TITLE
Cannot scale datanode when running in swarm

### ISSUE THREAD

**Issue by ablimita** [big-data-europe/docker-hadoop#83]
I successfully ran hadoop in docker swarm using "docker-compose-v3.yml" . However, I was unable to scale datanode using "docker service scale hadoop_datanode=3". 

I updated *docker-compose-v3.yml* as below. All 3 datanodes started but only the first one got registered with the namenode. The other 2 datanodes are running, but not registered. I didn't see any error in service logs. Any solution for it? 

```
version: '3'

services:
  namenode:
    image: bde2020/hadoop-namenode:3.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - HADOOP_ROOT_LOGGER=DEBUG,console
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: hbase
        traefik.port: 9870

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    volumes:
      - /hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      HADOOP_ROOT_LOGGER: DEBUG,console
      SERVICE_PRECONDITION: "namenode:9870"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: hbase
        traefik.port: 9864

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    ports: 
      - 8088:8088
    environment:
            SERVICE_PRECONDITION: "namenode:9870 namenode:9000 datanode:9864"
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: hbase
        traefik.port: 8088

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    ports: 
      - 8042:8042
    environment:
            SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: hbase
        traefik.port: 8042

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
            SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.docker.network: hbase
        traefik.port: 8188

volumes:
  namenode:
  hadoop_historyserver:

networks:
  hbase:
    external:
      name: hbase

```

**Comment by Alibm73-zz** [comment]
@carawantech that's because you don't have 3 datanodes. you only have 1 datanode.

**Comment by Alibm73-zz** [comment]
in your yaml file:
```yml
datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    volumes:
      - /hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      HADOOP_ROOT_LOGGER: DEBUG,console
      SERVICE_PRECONDITION: "namenode:9870"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: hbase
        traefik.port: 9864
```
this sections:
```yml
 deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
```
it says create 1 datanode, because ```replicas: 1```. so in order to scale it you have to change it to   ```replicas: 3```. but it's also not good because you are creating 3 replicas on your only server. if the server gets exploded, all of your services will be lost

**Comment by Alibm73-zz** [comment]
@carawantech also can you post your traefik.yaml and traefik.toml file??

**Comment by ablimita** [comment]
@Alibm73 
> @carawantech that's because you don't have 3 datanodes. you only have 1 datanode.

I am not sure it makes difference specifying replication = 1 and then scale it to 3, or just specifying replication=3 in the yaml file. Anyway, I had tested both ways. None of them worked; only one datanode has been registered with namenode.

After looking into the logs more carefully, I realized that, during the registration, what namenode receives is the IP of the internal load balancer, not the IP of each individual datanode; therefore, when these 3 datanodes request registration, the name node receives the same load balancer IP 3 times. So no real registration happens.

I don't know how to compel the datanodes (or docker) to send the container IP, instead of load balancer IP, to the namenode.

BTW, above yml file worked well with local kubernetes. Scaling worked very well too. Apparently, docker swarm may not be the best choice here.

**Comment by Alibm73-zz** [comment]
imagine you have 3 servers (test1-3), and the test1 is the master in swarm.
now you want to deploy the namenode on the test1, and 2 datanodes on server2 and 3 datanodes on server 3 for example. so this would be your yml file
```yml
version: '3'

services:
  namenode:
    image: test1:5000/bde2020/hadoop-namenode:1
    ... [your config]
    networks:
      - hbase
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == test1

  datanode-test2:
    image: test1:5000/bde2020/hadoop-datanode:1
    ... [your config]
    networks:
      - hbase
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == test2

  datanode-test3:
    image: test1:5000/bde2020/hadoop-datanode:1
    ... [your config]
    networks:
      - hbase
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == test3

networks:
  hbase:
    external: true
```
you need to go to test1 and use ```docker stack deploy``` command. now you have 1 namenode and 5 datanodes (2 on test2 and 3 on test3)
